class Autogenerated {
  late List<About> about;

  Autogenerated({required this.about});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['about'] != null) {
      about = [];
      json['about'].forEach((v) {
        about.add(new About.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.about != null) {
      data['about'] = this.about.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class About {
  late int postId;
 late int id;
 late String name;
 late String email;
 late String body;

  About({required this.postId,required this.id,required this.name,required this.email,required this.body});

  About.fromJson(Map<String, dynamic> json) {
    postId = json['postId'];
    id = json['id'];
    name = json['name'];
    email = json['email'];
    body = json['body'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['postId'] = this.postId;
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['body'] = this.body;
    return data;
  }
}