import 'Model.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class RepositoryImpl{

  Future<List<About>> getAbout() async {
    http.Response response;
      response = await http.get(
          Uri.https("jsonplaceholder.typicode.com","/comments"),
      );
    if (response.statusCode == 200) {
      var data = json.decode(response.body);
      List<About> about =  Autogenerated.fromJson({"about" : data}).about;
      return about;
    } else {
      throw Exception();
    }
  }
}